Correct App theme
VeryOpenSource/uome2_client pull request #17
Opened 2022-03-20 11:24 UTC by getch04

reopen the issue to correct app theme

2022-03-20 18:02 UTC, hellyab commented
@getch04 can you also link the issue?

2022-03-20 20:21 UTC, hellyab requested changes

2022-03-20 20:21 UTC, hellyab commented on lib/core/theme/theme.dart
> +import 'package:flutter/material.dart';
let's rename the folder to `themes`

2022-03-20 20:21 UTC, hellyab commented on lib/core/theme/text_style.dart
> +      // fontWeight: FontWeight.w300,
remove commented code

2022-03-20 20:21 UTC, hellyab commented on lib/core/theme/theme.dart
> +import 'package:flutter/material.dart';
also, let's not use the same name as the folder on a file except on a barrel file.

2022-03-20 20:21 UTC, hellyab commented on lib/core/theme/colors.dart
> +  const AppColors._();
are we using this?

2022-03-20 20:21 UTC, hellyab commented on lib/main.dart
> +import 'package:uome2/core/theme/colors.dart';
We could avoid the redundant imports if we use barrel files

2022-03-20 20:21 UTC, hellyab commented on lib/main.dart
> +      color: AppColors.lightGreyColor,
Let's sort properties whenever we can.

2022-03-20 20:22 UTC, hellyab commented
@getch04 why are the colors for the big heading texts grayed out? And the button color looks a bit pale too.

2022-03-20 20:29 UTC, getch04 commented on lib/core/theme/colors.dart
> +  const AppColors._();
yes, this is a color constant that we are gonna use throughout the app. if there is any better way, that would be appreciated!

2022-03-22 17:01 UTC, hellyab requested changes
Still got a few comments but it's looking good.

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_colors.dart
> +  const AppColors._();
Can't we just make it `const AppColors()` ?

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_colors.dart
> +  static const primaryBlackColor = Colors.black;
Do we need this?

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_colors.dart
> +  static const primaryBackgroundColor = Color(0xFFFAFAFA);
Name it just background

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_colors.dart
> +  static const whiteColor = Color(0xffffffff);
We don't need this

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_text_style.dart
> +  AppTextStyle._();
This too

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_text_style.dart
> +  static TextTheme textTheme = TextTheme(
Is the screenshot updated to show this?

2022-03-22 17:01 UTC, hellyab commented on lib/core/themes/app_theme.dart
> +      textTheme: AppTextStyle.textTheme,
Sort properties whenever you can

2022-03-23 11:47 UTC, getch04 commented on lib/core/themes/app_colors.dart
> +  static const primaryBlackColor = Colors.black;
black? nope

2022-03-23 11:48 UTC, getch04 commented on lib/core/themes/app_colors.dart
> +  const AppColors._();
sure we can

2022-03-23 11:49 UTC, getch04 commented on lib/core/themes/app_theme.dart
> +      textTheme: AppTextStyle.textTheme,
consider it is done

2022-03-23 20:18 UTC, hellyab approved these changes
🥇 LGTM

2022-03-25 10:30 UTC, hellyab commented
@getch04 can we make the yellow a bit darker? Also black might look more visible on the yellow bg.

2022-03-31 00:00 UTC, hellyab approved these changes
LGTM

2022-03-31 00:05 UTC, merged